name: Pre-commit

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies and run pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pre-commit install
        pre-commit run --all-files
